openapi: 3.0.3
info:
  title: Robot 2.0 API
  version: 0.1.0
servers:
  - url: https://api.example.com
paths:
  /api/v1/items:
    get:
      summary: Get items
      responses: { "200": { description: OK } }
    post:
      summary: Create item
      responses: { "201": { description: Created } }
  /api/v1/items/{id}:
    delete:
      summary: Delete item
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses: { "204": { description: No Content } }